ephoto/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gallery.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^progressbarupload/', include('progressbarupload.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.contrib import admin
# Register your models here.
from django.conf.urls import url, include
from django.urls import path
from .views import ImageListView, AlbumListView, AlbumListAdvancedView, AlbumDetailView, AlbumCreateView, ImageDetailView, AlbumUpdateView, MontageListView, SendToMontageView, MontageApiView, MontageListView, MontageDetailView, SubFolderDetailView
from . import views

admin.site.site_title = 'ePhoto Admin'
admin.site.site_header = 'ePhoto Admin'

urlpatterns = [
    path('',  AlbumListView.as_view(), name='albums_search'),
    path('upload/',  AlbumCreateView.as_view(), name='albums_upload'),
    path(r'search/', AlbumListView.as_view(), name='albums_search'),
    path(r'advanced_search/', AlbumListAdvancedView.as_view(), name='albums_advanced_search'),
    path('album/<int:pk>/', AlbumDetailView.as_view(), name='album-detail'),
    path('image/<int:pk>/', ImageDetailView.as_view(), name='image-detail'),
    path('album_edit/<int:pk>/', AlbumUpdateView.as_view(), name='album-update'),
    path('montage/', MontageListView.as_view(), name='montage-list'),
    path('montage_detail/<int:pk>/', MontageDetailView.as_view(), name='montage-detail-view'),
     path('subfolder/<int:pk>/', SubFolderDetailView.as_view(), name='subfolder-detail-view'),
    path('send_to_montage/', SendToMontageView.as_view(), name='montage-send'),
    path('montage_api/<str:date>/<str:pub>', MontageApiView.as_view(), name='montage-api'),


    path('accounts/', include('django.contrib.auth.urls')),



]

gallery/models.py
import uuid
from django.db import models
from django.contrib import admin
from django.core.files.storage import FileSystemStorage

from django.template.defaultfilters import slugify


PUBLICATIONS = (
	('ALL', 'All'),
	('LM', 'Le Mauricien'),
	('WK', 'Week-End'),
	('SCP', 'Scope'),
	('TRF', 'Turf'),
	('WEB', 'Web'),
	('NN', 'Autre'),
	)


class MontagePublicationFolder(models.Model):
	publication = models.CharField(choices=PUBLICATIONS, max_length=20, blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)
	publish_date =  models.DateField(null=True, blank=True)


	def __str__(self):
		return '{} du {}'.format(self.publication, self.publish_date)


	def cover(self):
		if self.montage_subfolder:
			return '{}'.format(self.montage_subfolder.all()[0].images.all()[0].file.url)
		return None


class MontageSubFolder(models.Model):
	publication_folder = models.ForeignKey('gallery.MontagePublicationFolder', null=True, blank=True, related_name='montage_subfolder', editable=True, on_delete=models.SET_NULL)
	title = models.CharField(max_length=244, blank=True, null=True)
	images = models.ManyToManyField('gallery.Image', blank=True, related_name="montage_images")

	def __str__(self):
		return '{}'.format(self.title)


	def cover(self):
		if self.images:
			return '{}'.format(self.images.all()[0].file.url)
		return None



class Image(models.Model):
	album = models.ForeignKey('gallery.Album', null=True, blank=True, related_name="images", editable=True, on_delete=models.SET_NULL)
	title = models.CharField(max_length=244, blank=True, null=True)
	reference = models.CharField(max_length=244, blank=True, null=True)
	created =  models.DateTimeField(auto_now_add=True, null=True,)
	description =  models.CharField(max_length=244, blank=True, null=True)
	file = models.ImageField(upload_to='image/%Y/%m/%d', blank = True)


	
	def __unicode__(self):
		return self.title

	def __str__(self):
		return '{}'.format(self.title)


class Album(models.Model):

	is_visible = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now_add=True)
	slug = models.SlugField(max_length=50, unique=True, null=True, blank=True)
	tags = models.CharField(max_length=244, blank=True, null=True)
	title = models.CharField(max_length=244, blank=True, null=True)
	location = models.CharField(max_length=244, blank=True, null=True)
	author = models.CharField(max_length=244, blank=True, null=True)
	publication = models.CharField(choices=PUBLICATIONS, max_length=20, blank=True, null=True)
	publish_date =  models.DateTimeField(null=True, blank=True)
	photograph = models.ForeignKey('gallery.Photograph', related_name='album', null=True, blank=True, on_delete=models.SET_NULL)


	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		super(Album, self).save(*args, **kwargs)



	def __unicode__(self):
		return self.title

	def __str__(self):
		return '{0} ({1})'.format(self.title, self.publish_date)


	def photo_count(self):
		return self.images.count()


	def cover(self):
		cover = {'path':'https://cdn3.iconfinder.com/data/icons/abstract-1/512/no_image-512.png'}
		try:
			cover = self.images.first().file
		except:
			pass

		return cover



class Photograph(models.Model):
	name = models.CharField(max_length=244)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return '{0}'.format(self.name)

gallery/forms.py
from django import forms
from .models import Image, Album, Photograph
from django.forms import inlineformset_factory
from django.forms.models import BaseInlineFormSet
from gallery.models import PUBLICATIONS

class AlbumSearchForm(forms.Form):
    publication = forms.ChoiceField(required=False,  choices=PUBLICATIONS, initial='', widget=forms.Select(attrs={'class': 'form-control'}))
    current_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'class': 'form-control datepicker'}))
    def __init__(self, *args, **kwargs):
        super(AlbumSearchForm, self).__init__(*args, **kwargs)



class AlbumSearchAdvancedForm(forms.Form):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    publication = forms.ChoiceField(required=False,  choices=PUBLICATIONS, initial='', widget=forms.Select(attrs={'class': 'form-control'}))
    start_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'class': 'form-control datepicker'}))
    end_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'class': 'form-control datepicker2'}))
    photograph = forms.ModelChoiceField(required=False, queryset=Photograph.objects.filter(is_active=True), label="photographer", widget=forms.Select(attrs={'class': 'form-control'}))
    
  


    def __init__(self, *args, **kwargs):
        super(AlbumSearchAdvancedForm, self).__init__(*args, **kwargs)




class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title','file', 'reference']


    #specifying required attribute on widget for validation on formset
    #title = forms.FileField(required=False, widget=forms.TextInput(attrs={'required': False}))
    file = forms.FileField(required=True, widget=forms.FileInput(attrs={'required': True}))
    reference = forms.CharField(required=True, widget=forms.TextInput(attrs={'required': True, }))





    def __init__(self, *args, **kwargs):
        super(ImageForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items(): 
            if field_name == 'file':
                field.widget.attrs['class'] = 'form-control-file'
            else:
                field.widget.attrs['class'] = 'form-control'



class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'publication', 'publish_date', 'photograph', 'location']


    title = forms.CharField(required=True)
    publication= forms.ChoiceField(required=True, choices=PUBLICATIONS)
    publish_date= forms.DateField(required=True)
    
    def __init__(self, *args, **kwargs):
        super(AlbumForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'publish_date':
                field.widget.attrs['class'] = 'form-control datepicker'
            else:
                field.widget.attrs['class'] = 'form-control'






ImageFormSet = inlineformset_factory(Album, Image, fields=('album',  'reference', 'title', 'file',), form=ImageForm, extra=1, can_delete=False,)

gallery/views.py
import datetime
import json
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core import serializers

from .forms import ImageForm, AlbumForm, ImageFormSet, AlbumSearchForm, AlbumSearchAdvancedForm
from .models import Image, Album, MontagePublicationFolder, MontageSubFolder
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.db import IntegrityError, transaction
from django.contrib import messages
from django.urls import reverse

from accounts.mixins import CustomLoginRequiredMixin
from .utils import publication_dates
from .models import PUBLICATIONS




def index(request):
	return render(request, 'upload_form.html', {})



class ImageListView(ListView):
	model = Image
	template_name = 'image_search.html'  # Default: <app_label>/<model_name>_list.html
	context_object_name = 'photos'  # Default: object_list
	paginate_by = 10
	queryset = Image.objects.all()  # Default: Model.objects.all()


class ImageDetailView(DetailView):
	model = Image
	template_name = 'image_detail_view.html'
	context_object_name = 'image'



class AlbumCreateView(CustomLoginRequiredMixin, CreateView):
	model = Album
	template_name = 'upload_form.html'
	form_class = AlbumForm


	def get(self, *args, **kwargs):
		self.object = None
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		image_form = ImageFormSet()

		return self.render_to_response(
			self.get_context_data(form=form, image_form=image_form)
			)

	def get_success_url(self):
		return reverse('album-detail', kwargs={'pk' : self.object.pk})

	
	def form_valid(self, form):
		ctx=self.get_context_data()
		images = ctx['image_form']

   
		with transaction.atomic():
			self.object = form.save()

			for image in images.forms:
				print('IMAGES', images)
				print('******')
			if images.is_valid():
				images.instance= self.object
				images.save()


		"""  with transaction.atomic():

				self.object = form.save()
				if images.is_valid():
					images.instance = self.object
					images.save()
		"""

		return super(AlbumCreateView, self).form_valid(form)




	def get_context_data(self, *args, **kwargs):
		ctx = super(AlbumCreateView, self).get_context_data(*args, **kwargs)
		if self.request.POST:
			ctx['form'] = AlbumForm(self.request.POST)
			ctx['image_form'] = ImageFormSet(data=self.request.POST, files=self.request.FILES)
		else:
			ctx['form'] = AlbumForm()
			ctx['image_form'] = ImageFormSet()

		return ctx
	   

  

class AlbumListAdvancedView(CustomLoginRequiredMixin, ListView):
	model = Album
	template_name = 'image_search_advanced.html'  
	context_object_name = 'album'
	form_class = AlbumSearchAdvancedForm
	paginate_by = 8
	allow_empty_first_page=True
	queryset = Album.objects.filter(is_visible=True).order_by('publish_date')

	def get_context_data(self, *args, **kwargs):
		ctx = super(AlbumListAdvancedView, self).get_context_data(*args, **kwargs)
		
		ctx['form'] = AlbumSearchAdvancedForm(self.request.GET)

		return ctx

	def get_queryset(self):
		form = self.form_class(self.request.GET)

		if form.is_valid():

			title = form.cleaned_data['title']
			publication = form.cleaned_data['publication']
			photograph = form.cleaned_data['photograph']
			start_date = form.cleaned_data['start_date']
			end_date = form.cleaned_data['end_date']
			filters = {'is_visible':True}


			if title:
				filters['title__icontains'] = title

			if photograph:
				filters['photograph__name'] = photograph

			if start_date:
				filters['publish_date__gte'] = start_date
	   

			if end_date:
				filters['publish_date__lte'] = end_date


			if (publication) and (publication != 'ALL'):
				filters['publication'] = publication

			print('FILTERS',filters)

			object_list = self.model.objects.filter(**filters).order_by('created')
			return object_list    
		
			
	   
		return Album.objects.filter(is_visible=True).order_by('publish_date')


class AlbumListView(CustomLoginRequiredMixin, ListView):
	model = Album
	template_name = 'image_search.html'  
	context_object_name = 'album'
	form_class = AlbumSearchForm
	paginate_by = 8
	allow_empty_first_page=True
	queryset = Album.objects.filter(is_visible=True).order_by('publish_date')

	def get_context_data(self, *args, **kwargs):
		ctx = super(AlbumListView, self).get_context_data(*args, **kwargs)
		
		ctx['form'] = AlbumSearchForm(self.request.GET)

		return ctx

	def get_queryset(self):
		form = self.form_class(self.request.GET)

		if form.is_valid():

			publication = form.cleaned_data['publication']
			current_date = form.cleaned_data['current_date']
			filters = {'is_visible':True}

			if current_date:
				filters['publish_date__date'] = current_date
			else:
				filters['publish_date__date'] = datetime.datetime.today()
				
				
	   
			if (publication) and (publication != 'ALL'):
				filters['publication'] = publication

			print('FILTERS',filters)


			object_list = self.model.objects.filter(**filters).order_by('created')
			return object_list    
		
		
		
	   
		return Album.objects.filter(is_visible=True).order_by('publish_date')


class AlbumDetailView(CustomLoginRequiredMixin, DetailView):
	model = Album
	context_object_name = 'album'
	template_name = 'album_detail_view.html'

	def get_context_data(self, *args, **kwargs):
		ctx = super(AlbumDetailView, self).get_context_data(*args, **kwargs)
		pub_dates = {'LM':publication_dates(), 
							'WK':publication_dates(publication='WK'), 
							'SCP':publication_dates(publication='SCP'), 
							'TRF':publication_dates(publication='TRF') }
		ctx['pub_dates'] = pub_dates
		ctx['publications']= PUBLICATIONS
		ctx['images'] = self.request.GET.get('images', None)

		return ctx



class AlbumUpdateView(CustomLoginRequiredMixin, UpdateView):
	model = Album
	context_object_name = 'album'
	template_name = 'album_update_view.html'
	form_class = AlbumForm

	def get_success_url(self):
		return reverse('album-detail', kwargs={'pk' : self.object.pk})




class MontageListView(CustomLoginRequiredMixin, ListView):
	model = MontagePublicationFolder
	context_object_name = 'publications'
	template_name = 'montage_list_view.html'
	from_date = datetime.datetime.now() - datetime.timedelta(days=7)
	queryset = MontagePublicationFolder.objects.filter(publish_date__range=[from_date, datetime.datetime.now()])


	def get_queryset(self):

		publication = self.request.GET.get("p", None)
		return MontagePublicationFolder.objects.filter(publication=publication, publish_date__range=[self.from_date, datetime.datetime.now()])



class MontageDetailView(CustomLoginRequiredMixin, ListView):
	model = MontageSubFolder
	context_object_name = 'subfolders'
	template_name = 'montage_sub_list_view.html'


	def get_queryset(self):

		publication_folder_id = self.kwargs.get('pk')
		print('publication_folder_id', publication_folder_id)
		return MontageSubFolder.objects.filter(publication_folder=publication_folder_id)


class SubFolderDetailView(CustomLoginRequiredMixin, DetailView):
	model = MontageSubFolder
	context_object_name = 'subfolder'
	template_name = 'subfolder_detail_view.html'


	




class MontageApiView(CustomLoginRequiredMixin, DetailView):

	def get(self, *args, **kwargs):
		publish_date = self.kwargs.get('date')
		publication = self.kwargs.get('pub')
		print(publish_date, 'date')
		montage_pub = MontagePublicationFolder
		data = {}
		try:
			montage_pub_obj = montage_pub.objects.get(publish_date=publish_date, publication=publication)
			data = serializers.serialize('json', montage_pub_obj.montage_subfolder.all(), fields=('title','pk'))
		
		except montage_pub.DoesNotExist:
			print('does not exist')
			return JsonResponse({ 'status':False,'message':'main folder not found', 'data':None}, status=400)

		return HttpResponse(data, content_type="application/json")



class SendToMontageView(CustomLoginRequiredMixin, TemplateView):
	template_name = 'send_to_montage.html'

	"""
	def get(self, request, *args, **kwargs):
		pass
	"""
	def post(self, *args, **kwargs):
		#print(self.request.POST)

		publication = self.request.POST.get('publication', None)
		pub_date = self.request.POST.get('pub_date', None)
		images = self.request.POST.get('images', None)
		dossier_id = self.request.POST.get('dossier', None)
		new_dossier = self.request.POST.get('new_dossier', None)


		print('publication : ', publication)
		print('pub-date : ', pub_date)
		print('images : ', images)
		print('dossier_id : ', dossier_id)
		print('new_dossier : ', new_dossier)


		with transaction.atomic():
			montage_pub_obj, created = MontagePublicationFolder.objects.get_or_create(publication=publication, publish_date=pub_date)
			
			subfolder_filters = {'publication_folder':montage_pub_obj,
						'title':new_dossier
						}

			if dossier_id == 'new':
				pass
			else:
				subfolder_filters['id']=dossier_id


		
			montage_subfolder_obj, created = MontageSubFolder.objects.get_or_create(**subfolder_filters)

			for i in images.split(','):
				montage_subfolder_obj.images.add(int(i))

			montage_subfolder_obj.save()

			



			print(montage_pub_obj)


		
		return self.render_to_response(self.get_context_data(**kwargs))

gallery/templates/album_detail_view.html
{% extends 'base.html' %}



{% block content %}

<div class="container">
<!-- Modal START -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Transfer to montage</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
					<!-- FORM START -->
				<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div id="selected_images"></div>
						<form id="montageForm" method='POST' action='/send_to_montage/'>
						{% csrf_token %}
							<div class="form-group">
								<label for="pub1" >Publication</label>
								<select id="publications" name="publication" class="form-control">
									<option selected disabled>-----Choose publication---</option>
									{% for pub in publications %}
									 {% if pub.0 != 'ALL' and pub.0 != 'WEB'  and pub.0 != 'NN'  %}

										<option value="{{pub.0}}">{{pub.1}}</option>
										{% endif %}
									{% endfor %}
								</select>
							</div>

								<div class="form-group">
									<label>Publication date</label>
									<select id="pub-dates" name="pub_date" class='form-control'>
												
										
									</select>
								</div>

								<div class="form-group">
									<label>Dossiers</label>
									<select id="dossiers" name="dossier" class='form-control'>


									</select>
								</div>

								<div id="new-dossier-container" class="form-group" style="display:none">
									<label>New dossier name</label>
									<input id="new-dossier-input" name="new_dossier" type="text" class='form-control'>
								</div>

								<input class="btn btn-sm btn-success" type="submit" value="submit">

						</form>

					</div>
				</div>
			</div>
					 <!-- FORM END -->
			</div>
		 
		</div>
	</div>
</div>
</div>
<!-- Modal END -->


<div class="container-fluid">

	<div class="row">
		 <div class="col-sm">
			<a href="/album_edit/{{album.id}}" class="btn btn-dark btn-sm btn-warning">Modify album</a>
		</div>
		<div class="col-sm">
			<button id="selectMontageBtn" class="btn-sm btn-success">Select for Montage</button>
			 <button id="toMontageBtn" type="button" class="btn btn-sm btn-info "  data-target="#exampleModal" style="display:none">Transfer to montage</button>
		</div>
		<div class="col-sm">
				<button id="closeMontageBtn" class="btn btn-dark btn-sm btn-info" style="display:none">Cancel</button>
		</div>
	</div>
<hr>

<h4 class="album_title">Title : {{album.title}}</h4>
<h6 class="album_title">Photographer : {{album.photograph.name}}</h6>
<h6 class="album_title">Date : {{album.publish_date |date:"d-M-Y"  }}</h6>
<div id="selectMontageTxt" class="alert alert-warning alert-dismissible fade show" role="alert" style='display:none;' >
			Click on the images to select for montage
			
		</div>
	 <form id="imageForm"> 
	<div class="row">
 
				 {% for image in album.images.all %}
		<div class="col-md-4 col-sm-12 col-lg-3">
				<div class="card mx-auto">
					<a class="image_href" href="#" onclick="window.open('/image/{{image.id}}','targetWindow', 'toolbar=no, location=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=640, height=480');"><img class="card-img-top selectable checkable" src="{{ image.file.url }}"  height="150"> </a>
					 <input class="montageCheckbox" type="checkbox" name="{{image.id}}" style="display:none"> 
					<div class="card-body">
						<div class="card-text" >
							<a href="{{image.file.url}}" target="_blank"><strong>Ref : {{ image.reference }} </strong></a> 
								<div>{{ image.title }}</div>
								<div>{{ image.created |date:"d-M-Y"  }}</div>
								
						 
						</div>
				</div>
			</div>
		</div>
	 {% endfor %}

	</div>
			</form>
</div>




{% endblock %}




{% block script_after %}
{% load staticfiles %}
<script src="{% static 'jquery.imgcheckbox.js' %}" type="text/javascript" ></script>
{% endblock %}

{% block script_before %}
<script type='text/javascript'>
var num = {{pub_dates |safe}};

</script>

{% endblock %}

gallery/templates/album_update_view.html
{% extends 'base.html' %}



{% block content %}

<div class="container">
<div class="row">
  <div class='column'>
      <a href="/album/{{album.id}}" class="btn btn-dark btn-sm btn-warning">  &larr; Back to album </a>
      <br/>
      <br/>
  </div>
</div>
<div class="row">

  <div class="colum">
{% if form.errors %}

    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
  {% endif %}
  </div>
</div>


<div class="row">
  <div class="column">

  <form  enctype="multipart/form-data" method="POST" class="form-white-bg">
  
  <legend>Create album:</legend>
    
      {% csrf_token %}
    <div class="form-group">
      {{ form.as_p }}
    </div>
   
    <input type="submit" value="submit" class='btn btn-success btn-sm'>

  </form>
  </div>
</div>
</div>



{% endblock %}

gallery/templates/album_view.html
{% extends 'base.html' %}



{% block content %}





<div class="container-fluid">
  <div class="row">
    <div class="col-sm">
        <div class="image_count">{{count}} photos</div>
    </div>
    <div class="col-sm">
      <button id="selectMontageBtn" class="btn-sm btn-success">Select for Montage</button>
      <button id="toMontageBtn" class="btn-sm btn-danger" style="display:none">Transfer to Montage</button>
    </div>
    <div class="col-sm">
        <button id="closeMontageBtn" class="btn btn-sm btn-info" style="display:none">Cancel</button>
    </div>
    <div class="col-sm">
        <a id="closeMontageBtn" class="btn btn-dark btn-sm btn-warning ">Modify album details</a>
    </div>
  </div>
<hr>


  <div class="row">
         {% for photo in photos %}
    <div class="col-6 col-md-12 col-lg-3 mb-12">
        <div class="card mx-auto">
          <a href="/image/{{photo.id}}"  onclick="window.open(this.href,'targetWindow', 'toolbar=no, location=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=640, height=480');"><img class="card-img-top" src="{{ photo.thumb.url }}"  height="150"> </a>
          <div class="card-body">
            <div class="card-text" >
              <a href="/image/{{photo.id}}" ><strong>Refé : {{ photo.reference }} </strong></a> 
                <div>Légende: {{ photo.description }}</div>
                <input class="montageCheckbox" type="checkbox" name="photo.id" style="display:none">
             
            </div>
        </div>
      </div>
    </div>
   {% endfor %}
  </div>
</div>
 



{% endblock %}

gallery/templates/image_detail_view.html
<html>
<head>
<title>{{image.title}} from {{image.album.title}}</title>

<style>

body {
  background-color:#f8f9fa;
  padding:10px;
}
table {
  border-collapse: collapse;
}

table, th, td {
  border: 1px solid black;
  text-align:left;
}

a {
  padding:10px;
  margin:10px 0px;
  background-color:#ff9800;
  color:#fff;
  border-radius:3px;
  text-decoration: none;

}

img{
  margin:20px 0;
}

</style>
</head>
<body>

  <table>
    <tr><th>Details</th></tr>
    <tr><th>Title</th><td>{{image.title}}</td></tr>
    <tr><th>Ref</th><td>{{image.reference}}</td></tr>
    <tr><th>Date</th><td>{{image.created}}</td></tr>
    <tr><th>Album</th><td>{{image.album.title}}</td></tr>
  </table>
  <br>
  <a href="{{ image.file.url }}" download>Download image</a>

  
  <img class="card-img-top" src="{{ image.file.url }}"  width="100%" height="auto"/> 
  <br>
  <br>
</body>
</html>

gallery/templates/montage_list_view.html
{% extends 'base.html' %}


{% block content %}

<div class="container-fluid">
  {% if publications %}
    <h3>Displaying from last 7 days</h3>
    <div class="row">

      



      {% for pub in publications %}
      <div class="col-md-4 col-sm-12 col-lg-3">
          <div class="card mx-auto">
            <a href="/montage_detail/{{pub.id}}/"><img class="card-img-top" src="{{ pub.cover }}"  height="150"> </a>
            <div class="card-body">
              <div class="card-text" >
                <a href="{{image.file.url}}" target="_blank"><strong>{{pub.get_publication_display}} du {{ pub.publish_date |date:"D, d M Y" }} </strong></a> 
                  <div>{{ pub.created }}</div>
               
              </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

  {% else %}
  <div class="row">
   <div class="column">
              <div class="alert alert-warning">
               <strong>No results !</strong> No results found matching your query
              </div>
    </div>
  </div>
     {% endif %}

</div>
       



{% endblock %}